# Numpy

In [1]:
L1 = [3,4,5]
L2 = [7,8,9]

In [2]:
type(L1)

list

In [3]:
type(L1[0])

int

In [4]:
L1 + L2

[3, 4, 5, 7, 8, 9]

In [18]:
%%time
L3 = []
for i in range(len(L1)):
    L3.append(L1[i] + L2[i])

CPU times: user 12 µs, sys: 1 µs, total: 13 µs
Wall time: 17.9 µs


In [17]:
L3

[10, 12, 14]

### Importando Numpy

In [8]:
import numpy as np

In [9]:
np.__version__

'1.19.5'

In [12]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [13]:
L1_n = np.array([3,4,5])
L2_n = np.array([7,8,9])

In [14]:
type(L1_n)

numpy.ndarray

In [19]:
%%time
L1_n + L2_n

CPU times: user 38 µs, sys: 4 µs, total: 42 µs
Wall time: 53.9 µs


array([10, 12, 14])

In [20]:
import time as tm

In [42]:
tm.time()

1662044989.6920261

In [45]:
def sumaListas(N):
    t1 = tm.time()
    L1 = range(N)
    L2 = range(N)
    
    L3 = []
    for i in range(len(L1)):
        L3.append(L1[i] + L2[i])
    
    return tm.time() - t1

In [47]:
sumaListas(10000000)

4.9305970668792725

In [48]:
def sumaNumpy(N):
    t1 = tm.time()
    L1_n = np.arange(N)
    L2_n = np.arange(N)
    
    L3_n = L1_n + L2_n
    
    return tm.time() - t1

In [49]:
sumaNumpy(10000000)

0.24957799911499023

## Funciones/Propiedades Numpy

In [50]:
L1_n

array([3, 4, 5])

In [51]:
type(L1_n)

numpy.ndarray

In [52]:
type(L1_n[0])

numpy.int64

In [54]:
L1_n.dtype

dtype('int64')

In [57]:
L1_n = L1_n.astype('int8')

In [58]:
L1_n.dtype

dtype('int8')

In [59]:
np.random.randint(-5,5,10)

array([ 2,  3,  4,  1, -1,  1,  1, -1,  0, -5])

In [60]:
np.random.randint(-3,3,(3,3))

array([[-1,  1, -1],
       [-3,  0,  1],
       [ 0, -2, -3]])

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [64]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
#matriz de 3,4 con valores -7

np.ones((3,4))*-7

array([[-7., -7., -7., -7.],
       [-7., -7., -7., -7.],
       [-7., -7., -7., -7.]])

In [68]:
np.full((3,4),-7)

array([[-7, -7, -7, -7],
       [-7, -7, -7, -7],
       [-7, -7, -7, -7]])

## Indexing/Slicing

In [71]:
M = np.random.randint(-3,3,(3,5))
M

array([[-3, -2,  2, -1, -3],
       [-1,  1, -3, -1,  1],
       [ 2, -3, -2,  1, -1]])

In [72]:
M[0,:]

array([-3, -2,  2, -1, -3])

In [73]:
M[:,-1]

array([-3,  1, -1])

In [75]:
M[1:,2:4]

array([[-3, -1],
       [-2,  1]])

In [76]:
M

array([[-3, -2,  2, -1, -3],
       [-1,  1, -3, -1,  1],
       [ 2, -3, -2,  1, -1]])

In [77]:
M.T

array([[-3, -1,  2],
       [-2,  1, -3],
       [ 2, -3, -2],
       [-1, -1,  1],
       [-3,  1, -1]])

In [78]:
M[::-1]

array([[ 2, -3, -2,  1, -1],
       [-1,  1, -3, -1,  1],
       [-3, -2,  2, -1, -3]])

Ejercicio:
    
    1. Crear una función que reciba 7 valores de entrada:
        
        val1 = cantidad de filas
        val2 = cantidad de columnas
        val3 = px_ini
        val4 = py_ini
        val5 = px_fin
        val6 = py_fin
        val7 = valor a buscar